- name: Add nginx repository
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/debian/ wheezy  nginx"
- name: Add nginx repository
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/debian/ wheezy nginx"

- name: download GPG key
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/tmp/nginx_signing.key

- name: accept GPG key
  command: "apt-key add /tmp/nginx_signing.key "
  tags:
    - nginx

- name: Install nginx
  apt:
    pkg: nginx
    update_cache: true
    state: installed
  tags:
    - nginx

- name: nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify:
    - restart nginx

- name: create sites-enabled directory
  file:
    path: "/etc/nginx/sites-enabled"
    state: "directory"


- name: create sites-available directory
  file:
    path: "/etc/nginx/sites-available"
    state: "directory"

- name: nginx proxy params
  template:
    src: proxy_params.j2
    dest: "/etc/nginx/proxy_params"
  notify:
    - restart nginx
        
    